<?php

namespace CoffeeShop\Condiment;

/**
 * Class Soy.
 */
class Soy extends AbstractCondimentDecorator
{
    /**
     * {@inheritdoc}
     */
    public function getDescription(): string
    {
        // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function cost(): int
    {
        // TODO: Implement cost() method.
    }
}
